-- imports para manipular arquivo e caracteres

import System.IO
import Data.Char(toUpper)
import Data.Char

-- funçao "main" onde define onde sera escrito e lido as strings para tradução

main::IO ()
main = do
  x <- readFile "projeto.txt"  			--leitura da string para traduçaõ do arquivo
  writeFile "traducao.txt"(sep1 x) 		-- escrita da traduçao no arquivo
 
 
 --funçao que vai dividir a lista de string em strings

 sep :: [String] -> String
sep [] = []
sep (a:b) = minus a ++ " " ++ sep b

--funçao que converte carateres maisculos em minusculos 

minus:: String -> String
minus cs = tradutor [toLower c | c <- cs] 	-- compreençao de lista
	
--funçao que traduz cada string (port-ing / ing-port)

tradutor:: String -> String
tradutor ("eu") = "i"
tradutor ("voce") =	"you"
tradutor ("eles") = "they"
tradutor ("ela") = "she"
tradutor ("ele") = "he"
tradutor ("azul") = "blue"
tradutor ("amarelo")  = "yellow"
tradutor ("vermelho") = "red"
tradutor ("preto") = "black"
tradutor ("verde") = "green"
tradutor ("rosa") = "pink"
tradutor ("roxo") = "purple"
tradutor ("branco")	= "white"
tradutor ("olho") = "eyes"
tradutor ("nariz") = "nose"
tradutor ("boca") = "mouth"
tradutor ("orelha") = "ear"
tradutor ("cabelo") = "hair"
tradutor ("cabeça") = "head"
tradutor ("mao") = "hand"
tradutor ("pe") = "foot"
tradutor ("perna") = "leg!"
tradutor ("peito") = "boob"
tradutor ("braço") = "arm"
tradutor ("ombro") = "shoulder"
tradutor ("camisa") = "shirt"
tradutor ("calça") = "pants"
tradutor ("relogio") = "clock"
tradutor ("brinco") = "earring"
tradutor ("colar") = "necklace"
tradutor ("anel") = "ring"
tradutor ("amor") = "love"
tradutor ("raiva") = "angry"
tradutor ("alegria") = "happy"
tradutor ("triste") = "sad"
tradutor ("sorrir") = "smille"
tradutor ("chorar") = "cry"
tradutor ("paixao") = "passion"
tradutor ("carro") = "car"
tradutor ("moto") = "motorcycle"
tradutor ("onibus") = "bus"
tradutor ("caminhão") = "truck"
tradutor ("trem") = "train"
tradutor ("futebol") = "soccer"
tradutor ("jogo") = "game"
tradutor ("amigo") = "friend"
tradutor ("pai") = "father"
tradutor ("mae") = "mother"
tradutor ("irmao") = "brother"
tradutor ("irma") = "sister"
tradutor ("tio") = "uncle"
tradutor ("tia") = "aunt"
tradutor ("primo") = "cousin"
tradutor ("subrinho") = "nephew"
tradutor ("chefe") = "boss"
tradutor ("livro") = "book"
tradutor ("caneta") = "pen"
tradutor ("lapis") = "pencil"
tradutor ("borracha") = "eraser"
tradutor ("caderno") = "notebook"
tradutor ("computadpr") = "computer"
tradutor ("quente") = "hot"
tradutor ("frio") = "cold"
tradutor ("vento") = "wind"
tradutor ("fogo") = "fire"
tradutor ("terrra") = "earth"
tradutor ("agua") = "water"
tradutor ("oculos") = "glass"
tradutor ("sol") = "sun"
tradutor ("lua") = "moon"
tradutor ("planta") = "plant"
tradutor ("cama") = "bed"
tradutor ("cachorro") = "dog"
tradutor ("gato") = "cat"
tradutor ("ganso") = "goose"
tradutor ("pato") = "duck"
tradutor ("galinha") = "chicken"
tradutor ("leao") = "leon"
tradutor ("girrafa") = "girrafe"
tradutor ("passaro") = "bird"
tradutor ("violao") = "guitar"
tradutor ("bateria") = "drums"
tradutor ("aviao") = "airplane"
tradutor ("professor") = "teacher"
tradutor ("namorada") = "girlfriend"
tradutor ("namorado") = "boyfriend"
tradutor ("luz") = "light"
tradutor ("cidade") = "city"
tradutor ("pais") = "country"
tradutor ("cavalo") = "horse"
tradutor ("rato") = "mouse"
tradutor ("arma") = "gun"
tradutor ("trabalho") = "job"
tradutor ("cantar") = "sing"
tradutor ("andar") = "walk"
tradutor ("mundo") = "world"
tradutor ("bonito") = "beautiful"
tradutor ("urso") = "bear"
tradutor ("melhor") = "best"
tradutor ("nadar") = "swin"

tradutor ("i") = "eu"
tradutor ("you") =	"voce"
tradutor ("they") = "eles"
tradutor ("she") = "ela"
tradutor ("he") = "ele"
tradutor ("blue") = "azul"
tradutor ("yellow")  = "amarelo"
tradutor ("red") = "vermelho"
tradutor ("black") = "preto"
tradutor ("green") = "verde"
tradutor ("pink") = "rosa"
tradutor ("purple") = "roxo"
tradutor ("white")	= "branco"
tradutor ("eyes") = "olho"
tradutor ("nose") = "nariz"
tradutor ("mouth") = "boca"
tradutor ("ear") = "orelha"
tradutor ("hair") = "cabelo"
tradutor ("head") = "cabeça"
tradutor ("hand") = "mao"
tradutor ("foot") = "pe"
tradutor ("leg") = "perna"
tradutor ("boob") = "peito"
tradutor ("arm") = "braço"
tradutor ("shoulder") = "ombro"
tradutor ("shirt") = "camisa"
tradutor ("pants") = "calça"
tradutor ("clock") = "relogio"
tradutor ("earring") = "brinco"
tradutor ("necklace") = "colar"
tradutor ("ring") = "anel"
tradutor ("love") = "amor"
tradutor ("angry") = "raiva"
tradutor ("happy") = "alegria"
tradutor ("sad") = "triste"
tradutor ("smille") = "sorrir"
tradutor ("cry") = "chorar"
tradutor ("passion") = "paixao"
tradutor ("car") = "carro"
tradutor ("motorcycle") = "moto"
tradutor ("bus") = "onibus"
tradutor ("truck") = "caminhao"
tradutor ("train") = "trem"
tradutor ("soccer") = "futebol"
tradutor ("game") = "jogo"
tradutor ("friend") = "amigo"
tradutor ("father") = "pai"
tradutor ("mother") = "mae"
tradutor ("brother") = "irmao"
tradutor ("sister") = "irma"
tradutor ("uncle") = "tio"
tradutor ("uncle") = "tia"
tradutor ("cousin") = "primo"
tradutor ("nephew") = "sobrinho"
tradutor ("boss") = "chefe"
tradutor ("book") = "livro"
tradutor ("pen") = "caneta"
tradutor ("pencil") = "lapis"
tradutor ("eraser") = "borracha"
tradutor ("notebook") = "caderno"
tradutor ("computer") = "computador"
tradutor ("hot") = "quente"
tradutor ("cold") = "frio"
tradutor ("wind") = "vento"
tradutor ("fire") = "fogo"
tradutor ("earth") = "terra"
tradutor ("water") = "agua"
tradutor ("glass") = "oculos"
tradutor ("sun") = "sol"
tradutor ("moon") = "lua"
tradutor ("plant") = "planta"
tradutor ("bed") = "cama"
tradutor ("dog") = "cachorro"
tradutor ("cat") = "gato"
tradutor ("goose") = "ganso"
tradutor ("duck") = "pato"
tradutor ("chicken") = "galinha"
tradutor ("leon") = "leao"
tradutor ("girrafe") = "girrafa"
tradutor ("bird") = "passaro"
tradutor ("guitar") = "violao"
tradutor ("drums") = "bateria"
tradutor ("airplane") = "aviao"
tradutor ("teacher") = "professor"
tradutor ("girlfriend") = "namorada"
tradutor ("boyfriend") = "namorado"
tradutor ("light") = "luz"
tradutor ("city") = "cidade"
tradutor ("country") = "pais"
tradutor ("horse") = "cavalo"
tradutor ("mouse") = "rato"
tradutor ("gun") = "arma"
tradutor ("job") = "trabalho"
tradutor ("sing") = "cantar"
tradutor ("walk") = "andar"
tradutor ("world") = "mundo"
tradutor ("beautiful") = "bonito"
tradutor ("bear") = "urso"
tradutor ("best") = "melhor"
tradutor ("swin") = "nadar"

tradutor x = x
 
-- funcao que separa as strings para traducao

sep1::String->String
sep1 x = sep (words x)



